# Generated by Django 6.0.3 on 2026-03-31 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estufa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=200)),
                ('tipo_cultivo', models.CharField(max_length=200)),
                ('capacidade_maxima', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='registro_climatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('origem_dado', models.CharField(max_length=200)),
                ('id_estufa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestrutura.estufa')),
            ],
        ),
    ]
