# Generated by Django 6.0.3 on 2026-04-07 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraestrutura', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registro_climatico',
            new_name='registroClimatico',
        ),
        migrations.AlterModelTable(
            name='estufa',
            table='estufa',
        ),
        migrations.AlterModelTable(
            name='registroclimatico',
            table='registro_climatico',
        ),
    ]
