# Generated by Django 6.0.3 on 2026-04-07 13:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestrutura', '0002_rename_registro_climatico_registroclimatico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estufa',
            name='capacidade_maxima',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='estufa',
            name='nome_setor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estufa',
            name='tipo_cultivo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='estufa',
            table=None,
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(choices=[('GE', 'Gerente da Estufa'), ('AG', 'Agrônomo'), ('OP', 'Operador de Manejo')], default='OP', max_length=2)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origem_dado', models.CharField(blank=True, max_length=50, null=True)),
                ('estufa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestrutura.estufa')),
            ],
        ),
        migrations.DeleteModel(
            name='registroClimatico',
        ),
    ]
