# Generated by Django 6.0.3 on 2026-03-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_insumo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('unidade_medida', models.CharField(max_length=200)),
                ('quantidade_estoque', models.CharField(max_length=200)),
                ('custo_unitario', models.CharField(max_length=200)),
            ],
        ),
    ]
