# Generated by Django 6.0.3 on 2026-04-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_insumo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('unidade_medida', models.CharField(max_length=20)),
                ('quantidade_estoque', models.IntegerField()),
                ('custo_unitario', models.FloatField()),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='ProdutoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('classificacao', models.CharField(max_length=50)),
                ('preco_venda', models.FloatField()),
                ('quantidade_estoque', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'produto_final',
            },
        ),
    ]
