# Generated by Django 4.2.11 on 2026-05-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data_movimentacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída'), ('Perda', 'Perda'), ('Ajuste', 'Ajuste')], max_length=15),
        ),
    ]
