# Generated by Django 6.0.3 on 2026-04-07 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_insumo_produtofinal_delete_estoque'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='insumo',
            table='insumo',
        ),
        migrations.AlterModelTable(
            name='produtofinal',
            table='produto_final',
        ),
    ]
