# Generated by Django 4.2.11 on 2026-05-19 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('lotePlantio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_colheita', models.DateField(auto_now_add=True)),
                ('quantidade_colhida', models.FloatField()),
                ('quantidade_perda', models.FloatField(default=0.0)),
                ('funcionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
                ('lote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotePlantio.loteplantio')),
            ],
            options={
                'db_table': 'colheita',
            },
        ),
    ]
