# Generated by Django 6.0.3 on 2026-04-10 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('lotePlantio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_colheita', models.DateField(auto_now_add=True)),
                ('quantidade_colhida', models.FloatField()),
                ('quantidade_perda', models.FloatField(default=0.0)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotePlantio.loteplantio')),
                ('produto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produtofinal')),
            ],
            options={
                'db_table': 'colheita',
            },
        ),
    ]
