# Generated by Django 4.2.11 on 2026-05-25 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIrrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valvula_id', models.CharField(max_length=50)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_atual', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='inativa', max_length=10)),
                ('fluxo_l_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('consumo_ciclo_l', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('mesa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_irrigacao', to='mesa.mesa')),
            ],
            options={
                'db_table': 'Registro_Irrigacao',
            },
        ),
        migrations.CreateModel(
            name='RegistroClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luminosidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ventilacao', models.IntegerField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('mesa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_clima', to='mesa.mesa')),
            ],
            options={
                'db_table': 'Registro_Clima',
            },
        ),
    ]
