# Generated by Django 6.0.3 on 2026-04-09 22:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estufa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origem_dado', models.CharField(blank=True, max_length=50, null=True)),
                ('estufa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estufa.estufa')),
            ],
        ),
    ]
