# Generated by Django 6.0.3 on 2026-04-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroClima', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registroclima',
            table='Registro_Clima',
        ),
    ]
