# Generated by Django 4.2.11 on 2026-05-19 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultura', '0001_initial'),
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotePlantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plantio', models.DateField()),
                ('status', models.CharField(choices=[('ES', 'Em Estoque'), ('BX', 'Estoque Baixo'), ('DI', 'Disponível'), ('AT', 'Ativo'), ('CO', 'Colhido'), ('PE', 'Perdido')], default='DI', max_length=2)),
                ('quantidade', models.FloatField(default=0.0)),
                ('unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('cultura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_plantio', to='cultura.cultura')),
                ('mesa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_plantio', to='mesa.mesa')),
            ],
            options={
                'db_table': 'lote_plantio',
            },
        ),
    ]
