# Generated by Django 6.0.3 on 2026-04-10 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estufa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotePlantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=100)),
                ('data_plantio', models.DateField()),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('CO', 'Colhido'), ('PE', 'Perdido')], default='AT', max_length=2)),
                ('custo_total', models.FloatField(default=0.0)),
                ('estufa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estufa.estufa')),
            ],
            options={
                'db_table': 'lote_plantio',
            },
        ),
    ]
