# Generated by Django 4.2.11 on 2026-04-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotePlantio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteplantio',
            name='custo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='loteplantio',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='loteplantio',
            name='quantidade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='loteplantio',
            name='unidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loteplantio',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loteplantio',
            name='status',
            field=models.CharField(choices=[('ES', 'Em Estoque'), ('BX', 'Estoque Baixo'), ('DI', 'Disponível'), ('AT', 'Ativo'), ('CO', 'Colhido'), ('PE', 'Perdido')], default='AT', max_length=2),
        ),
    ]
