# Generated by Django 6.0.3 on 2026-04-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionarios',
        ),
    ]
