# Generated by Django 4.2.11 on 2026-05-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('admin', 'Admin TI'), ('gerente', 'Gerente'), ('operador', 'Operador'), ('tecnico', 'Técnico')], max_length=50),
        ),
    ]
