# Generated by Django 4.2.11 on 2026-04-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('operador', 'Operador'), ('tecnico', 'Técnico')], max_length=50),
        ),
    ]
