# Generated by Django 4.2.11 on 2026-05-27 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
    ]
