# Generated by Django 4.2.11 on 2026-05-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estufa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=50)),
                ('capacidade_maxima', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status_mesa', models.CharField(default='livre', max_length=30)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('estufa', models.ForeignKey(db_column='estufa_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='estufa.estufa')),
            ],
            options={
                'db_table': 'mesa',
                'unique_together': {('estufa', 'identificacao')},
            },
        ),
    ]
