# Generated by Django 4.2.11 on 2026-05-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cultura', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tempo_medeio_colheita', models.IntegerField()),
                ('temperatura_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umidade_ideal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('obsersvacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
