# Generated by Django 4.2.11 on 2026-05-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultura',
            old_name='obsersvacoes',
            new_name='observacoes',
        ),
        migrations.RenameField(
            model_name='cultura',
            old_name='tempo_medeio_colheita',
            new_name='tempo_medio_colheita',
        ),
        migrations.AlterModelTable(
            name='cultura',
            table='cultura',
        ),
    ]
