# Generated by Django 4.2.11 on 2026-09-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0004_criar_cargos_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('FE', 'Fertilizante'), ('DF', 'Defensivo agrícola'), ('SB', 'Substrato'), ('OU', 'Outro')], default='OU', max_length=2)),
                ('unidade', models.CharField(max_length=20)),
                ('quantidade_atual', models.FloatField(default=0.0)),
                ('estoque_minimo', models.FloatField(default=0.0)),
                ('validade', models.DateField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimentacao', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída'), ('Perda', 'Perda'), ('Ajuste', 'Ajuste')], max_length=15)),
                ('quantidade', models.FloatField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('funcionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
                ('insumo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='insumo.insumo')),
            ],
            options={
                'db_table': 'movimentacao_insumo',
            },
        ),
    ]
