# Generated by Django 6.0.3 on 2026-04-09 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('estufa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotePlantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=100)),
                ('data_plantio', models.DateField()),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('CO', 'Colhido'), ('PE', 'Perdido')], default='AT', max_length=2)),
                ('custo_total', models.FloatField(default=0.0)),
                ('estufa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estufa.estufa')),
            ],
            options={
                'db_table': 'lote_plantio',
            },
        ),
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_colheita', models.DateField(auto_now_add=True)),
                ('quantidade_colhida', models.FloatField()),
                ('quantidade_perda', models.FloatField(default=0.0)),
                ('produto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produtofinal')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.loteplantio')),
            ],
            options={
                'db_table': 'colheita',
            },
        ),
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atividade', models.DateField(auto_now_add=True)),
                ('tipo_atividade', models.CharField(max_length=100)),
                ('quantidade_insumo_usada', models.FloatField()),
                ('custo_atividade', models.FloatField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.insumo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.loteplantio')),
            ],
            options={
                'db_table': 'manejo',
            },
        ),
    ]
