# Generated by Django 6.0.3 on 2026-04-07 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='colheita',
            table='colheita',
        ),
        migrations.AlterModelTable(
            name='loteplantio',
            table='lote_plantio',
        ),
        migrations.AlterModelTable(
            name='manejo',
            table='manejo',
        ),
    ]
