# Generated by Django 6.0.3 on 2026-04-10 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('lotePlantio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atividade', models.DateField(auto_now_add=True)),
                ('tipo_atividade', models.CharField(max_length=100)),
                ('quantidade_insumo_usada', models.FloatField()),
                ('custo_atividade', models.FloatField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.insumo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotePlantio.loteplantio')),
            ],
            options={
                'db_table': 'manejo',
            },
        ),
    ]
