# Generated by Django 6.0.3 on 2026-04-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estufa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=100)),
                ('tipo_cultivo', models.CharField(max_length=50)),
                ('capacidade_maxima', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
